prep-html-syntax - Simon Kim
Skim-329/prep-0721-code-solutions pull request #3
Opened 2021-07-31 23:21 UTC by Skim-329

<img width="1151" alt="Screen Shot 2021-07-31 at 4 14 39 PM" src="https://user-images.githubusercontent.com/88165545/127754519-bb1c53cd-459f-4282-82fa-3e6c2d5a1293.png">

2021-08-01 16:58 UTC, thebearingedge requested changes

2021-08-01 16:58 UTC, thebearingedge commented on prep-html-syntax/index.html
> +  </body>
Hi Simon, be sure to divide your page into two specific sections. The `<head>` should open and close before the `<body>` opens and closes. The visible content of the page should go in the `<body>`.

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- meta info like <title></title> goes in here -->
  </head>
  <body>
    <!-- visible content like <h1></h1> and <p></p> goes in here -->
  </body>
</html>
```

2021-08-03 04:57 UTC, Skim-329 reviewed
<img width="941" alt="Screen Shot 2021-08-02 at 9 55 02 PM" src="https://user-images.githubusercontent.com/88165545/127960030-1558659e-a811-4393-a753-83bb0db746d3.png">

2021-08-03 04:57 UTC, Skim-329 commented on prep-html-syntax/index.html
> +  </body>
Hey Tim, thanks for the clarification. By <head> are you referring to the <h1> that I used? Also, to make a change, should I just begin the assignment again?

2021-08-03 04:57 UTC, Skim-329 commented on prep-html-syntax/index.html
> +  </body>
*h1 designation.

2021-08-03 18:48 UTC, thebearingedge approved these changes

2021-08-03 18:48 UTC, thebearingedge commented on prep-html-syntax/index.html
> +  </body>
Hi @Skim-329 I was just referring to the missing `<head>` element. Looks good now!

2021-08-03 19:30 UTC, merged